/**
 * ==============================================================================
 * Supabase Schema & Data Sync Utility
 * ==============================================================================
 * This script connects to the active Supabase instance, fetches all public tables,
 * columns, constraints, RLS status, row counts, and sample records, and updates
 * SUPABASE_SCHEMA.md while maintaining a lightweight, concise file size.
 *
 * Usage:
 *   node scripts/sync-schema.js
 *   npm run db:sync
 * ==============================================================================
 */

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { createClient } from '@supabase/supabase-js';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const rootDir = path.resolve(__dirname, '..');

// 1. Parse .env file without external dependencies
function loadEnv() {
  const envPath = path.join(rootDir, '.env');
  const env = {};
  if (fs.existsSync(envPath)) {
    const lines = fs.readFileSync(envPath, 'utf8').split('\n');
    for (const line of lines) {
      const trimmed = line.trim();
      if (!trimmed || trimmed.startsWith('#')) continue;
      const match = trimmed.match(/^([^=]+)=(.*)$/);
      if (match) {
        const key = match[1].trim();
        let value = match[2].trim();
        if ((value.startsWith('"') && value.endsWith('"')) || (value.startsWith("'") && value.endsWith("'"))) {
          value = value.slice(1, -1);
        }
        env[key] = value;
      }
    }
  }
  return env;
}

const env = loadEnv();
const supabaseUrl = env.VITE_SUPABASE_URL || process.env.VITE_SUPABASE_URL;
const supabaseAnonKey = env.VITE_SUPABASE_ANON_KEY || process.env.VITE_SUPABASE_ANON_KEY;

if (!supabaseUrl || !supabaseAnonKey) {
  console.error('❌ Error: Missing VITE_SUPABASE_URL or VITE_SUPABASE_ANON_KEY in .env');
  process.exit(1);
}

const supabase = createClient(supabaseUrl, supabaseAnonKey);

async function syncSchema() {
  console.log('🔄 Fetching Supabase schema & data overview...');

  try {
    const { data, error } = await supabase.rpc('get_schema_overview');

    if (error) {
      throw error;
    }

    const { tables, generated_at } = data;
    const dateFormatted = new Date(generated_at || Date.now()).toUTCString();

    let markdown = `# Supabase Database Schema & Snapshot\n\n`;
    markdown += `> **Project URL:** \`${supabaseUrl}\`  \n`;
    markdown += `> **Last Synced:** \`${dateFormatted}\`  \n`;
    markdown += `> **Total Tables:** \`${tables.length}\`\n\n`;
    markdown += `*This document is auto-generated by \`npm run db:sync\`. It tracks database schema, constraints, and sample data while maintaining a clean, compact footprint.*\n\n`;
    markdown += `---\n\n`;

    // Table of Contents
    markdown += `## 📋 Table Index\n\n`;
    markdown += `| Table | Rows | RLS | Primary Key | Foreign Keys |\n`;
    markdown += `| :--- | :--- | :--- | :--- | :--- |\n`;

    for (const t of tables) {
      const pk = t.primary_keys ? t.primary_keys.join(', ') : '-';
      const fkCount = t.foreign_keys ? t.foreign_keys.length : 0;
      markdown += `| [\`${t.table_name}\`](#table-${t.table_name}) | \`${t.row_count}\` | ${t.rls_enabled ? '✅ Enabled' : '⚠️ Disabled'} | \`${pk}\` | \`${fkCount} relations\` |\n`;
    }
    markdown += `\n---\n\n`;

    // Detailed Table Sections
    for (const t of tables) {
      markdown += `## <a id="table-${t.table_name}"></a>📦 Table: \`${t.table_name}\`\n\n`;
      markdown += `- **Row Count:** \`${t.row_count}\`\n`;
      markdown += `- **RLS Enabled:** \`${t.rls_enabled ? 'Yes' : 'No'}\`\n`;

      if (t.foreign_keys && t.foreign_keys.length > 0) {
        markdown += `- **Foreign Keys:**\n`;
        for (const fk of t.foreign_keys) {
          markdown += `  - \`${fk.column}\` ➔ \`${fk.foreign_table}.${fk.foreign_column}\`\n`;
        }
      }
      markdown += `\n`;

      // Columns Table
      markdown += `### Schema Definition\n\n`;
      markdown += `| Column | Type | Nullable | Default | Key |\n`;
      markdown += `| :--- | :--- | :--- | :--- | :--- |\n`;

      for (const col of t.columns || []) {
        const isPk = t.primary_keys && t.primary_keys.includes(col.column_name);
        const fk = t.foreign_keys?.find((f) => f.column === col.column_name);
        let keyInfo = '-';
        if (isPk) keyInfo = '🔑 PK';
        else if (fk) keyInfo = `🔗 FK ➔ ${fk.foreign_table}`;

        const defaultVal = col.column_default ? `\`${col.column_default.replace(/::[a-z0-9_ ]+/gi, '')}\`` : '-';
        const nullable = col.is_nullable === 'YES' ? 'Yes' : '**No**';

        markdown += `| **\`${col.column_name}\`** | \`${col.data_type}\` | ${nullable} | ${defaultVal} | ${keyInfo} |\n`;
      }
      markdown += `\n`;

      // Sample Data (Compact preview up to 3 rows)
      markdown += `### Data Snapshot (Max 3 rows)\n\n`;
      if (!t.sample_data || t.sample_data.length === 0) {
        markdown += `*No records currently present in table.*\n\n`;
      } else {
        const headers = Object.keys(t.sample_data[0]);
        markdown += `| ` + headers.map((h) => `\`${h}\``).join(' | ') + ` |\n`;
        markdown += `| ` + headers.map(() => `:---`).join(' | ') + ` |\n`;

        for (const row of t.sample_data) {
          markdown +=
            `| ` +
            headers
              .map((h) => {
                let val = row[h];
                if (val === null || val === undefined) return `*null*`;
                if (typeof val === 'object') val = JSON.stringify(val);
                val = String(val);
                // Truncate long strings for compact display
                if (val.length > 35) val = val.substring(0, 32) + '...';
                return `\`${val.replace(/\|/g, '\\|')}\``;
              })
              .join(' | ') +
            ` |\n`;
        }
        markdown += `\n`;
      }

      markdown += `---\n\n`;
    }

    const outputPath = path.join(rootDir, 'SUPABASE_SCHEMA.md');
    fs.writeFileSync(outputPath, markdown, 'utf8');

    console.log(`✅ Supabase schema successfully written to ${outputPath}`);
    console.log(`📊 Tracked ${tables.length} tables (${tables.map((t) => t.table_name).join(', ')})`);
  } catch (err) {
    console.error('❌ Failed to sync schema:', err.message);
    process.exit(1);
  }
}

syncSchema();
